fix(validity_data.json): use 12 days for positive tests start day
lovasoa/sanipasse pull request #155
Opened 2022-01-04 22:52 UTC by nathaner

# Description

The french health pass is valid if a positive test is older than 11 days and younger than 6 months.
However, the 11th day is not included, hence the pass is valid on the 12th day after the positive
test.

# Current behaviour 

For now, TAC Verif detects a pass as invalid if it's the 11th day since the positive test. However, Sanipasse detects the pass as valid. 

# Expected behaviour 

Sanipasse should have the same detection rules as TAC Verif. 

# Steps followed to resolve this bug

- Tested a positive test today that was done 11 days ago (on december 24th 2021), TAC Verif detected it as invalid
- Called the TousAntiCovid help center to ask them how the date was calculated, they confirmed it was 11 days plus 1 day

2022-01-04 23:06 UTC, lovasoa requested changes
Bonjour @nathaner, et merci beaucoup de votre contribution ! 

 Le fichier validity_data.json,  qui contient les données de validation, est synchronisé automatiquement avec le même backend que TACVérif. Si il y a un bug dans la validation, il ne peut être que dans https://github.com/lovasoa/sanipasse/blob/master/src/lib/tac_verif_rules.ts

2022-01-04 23:08 UTC, lovasoa commented
Et voilà l'implémentation de référence: https://gitlab.inria.fr/tousanticovid-verif/tousanticovid-verif-android/-/blob/master/app/src/main/java/com/ingroupe/verify/anticovid/service/document/DccService.kt

2022-01-04 23:46 UTC, lovasoa commented
Je viens d'essayer avec un test positif qui a une date de prélèvement de "2022-01-03". En réglant la date de mon téléphone au 13 janvier à 23:59, TACVérif le définit comme invalide. En la réglant au 14 janvier à 00:00, il le définit comme valide. Le test devient donc bien valable après exactement 11 jours. Il me semble que l'implémentation actuelle de sanipasse est correcte.

2022-01-04 23:48 UTC, lovasoa commented
@nathaner : est-ce que vous pourriez m'envoyer en privé le passe sur lequel vous avez constaté une différence, et la date et l'heure à laquelle vous avez fait le test ? 
contact@ophir.dev

2022-01-05 17:31 UTC, nathaner commented
Salut @lovasoa, merci pour tes commentaires. Je regarderai le fichier `tac_verif_rules.ts` pour faire la modif au bon endroit. 

Concernant la règle de validation, j'ai testé le certificat qui date du 24 décembre 2021 à 10h20 en changeant l'heure du téléphone : il est devenu valide à partir du 5 janvier 2022 à 1h00 du matin (je suppose qu'ils se basent sur la timezone GMT...). As-tu effectué le test avec un certificat de rétablissement ? 

Je ne peux malheureusement pas te transmettre le QR Code du certificat. Cependant, je peux te transmettre certaines propriétés du JSON correspondant au QR Code si tu me dis lesquelles t'intéressent et si elles ne permettent pas de reformer le QR Code d'origine.

2022-01-05 17:44 UTC, lovasoa commented
> As-tu effectué le test avec un certificat de rétablissement ?

Oui:

```json
{
    "ver": "1.3.0",
    "nam": {
      "fn": "XXX",
      "fnt": "XXX",
      "gn": "XXX",
      "gnt": "XXX"
    },
    "dob": "1943-01-27",
    "r": [
      {
        "tg": "840539006",
        "fr": "2022-01-03",
        "co": "FR",
        "is": "APHP",
        "df": "2022-01-14",
        "du": "2022-07-02",
        "ci": "URN:UVCI:01:FR:XXX"
      }
    ]
  }
```

Est-ce que le tien est indiqué comme test ? `t` au lieu de `r` ?

2022-01-05 17:59 UTC, nathaner commented
Non c'est aussi un `r` : 
```json
{
  "hcert": {
    "ver": "1.3.0",
    "nam": {
      "fn": "*******",
      "fnt": "*******",
      "gn": "*******",
      "gnt": "*******",
    },
    "dob": "*******",
    "r": [
      {
        "tg": "*******",
        "fr": "2021-12-24",
        "co": "FR",
        "is": "APHP",
        "df": "2022-01-04",
        "du": "2022-06-22",
        "ci": "URN:UVCI:01:FR:*******",
      }
    ]
  },
```

2022-01-05 18:08 UTC, lovasoa commented
Ce passe, qui mentionne expressément une date de début de validité au 2022-01-04, n'est pas marqué comme valide dans TousAntiCovid-Vérif avant le 2022-01-05 à 1h du matin ? Cela me semble très étrange. Il me semble identique à celui que j'ai testé, et pour lequel le comportement de TousAntiCovid-Vérif correspond à [ce que l'on peut lire dans son code source public](https://gitlab.inria.fr/tousanticovid-verif/tousanticovid-verif-android/-/blob/master/app/src/main/java/com/ingroupe/verify/anticovid/service/document/DccService.kt#L434-437), ce qui est [annoncé publiquement par le gouvernement](https://www.gouvernement.fr/info-coronavirus/pass-sanitaire), et ce qui est indiqué dans le passe lui-même: `2022-01-04`.

2022-01-05 18:18 UTC, nathaner commented
Non, il n'est pas considéré comme valide jusqu'au 5 décembre à 1h00. Ça m'a paru étrange également que cela ne corresponde pas à ce qui est annoncé (11 jours à partir du test). C'est pourquoi j'ai appelé l'assistance de TousAntiCovid et ils m'ont confirmé que les tests de rétablissement étaient valides à partir de 11 jours exclus (donc 11 jours plus 1). 

J'avoue être surpris également que ton test de rétablissement fonctionne au bout de 11 jours inclus, il semble qu'il y ait deux comportements différents. La seule différence flagrante que je vois est que dans ton cas les 11 jours se situent dans le même mois. Dans le mien, ils se situent entre deux mois différents (décembre et janvier), et par conséquent entre deux années différentes. Pourrais-tu réaliser un test avec les mêmes dates que celui que j'ai utilisé ?

2022-01-05 20:33 UTC, lovasoa commented
Je ne peux pas vraiment faire de test sans avoir le passe en question. Peut-être que vous pourriez faire le test avec tacverif sur un autre téléphone ? Si vous arrivez à reproduire le problème de manière consistante, essayez peut-être de le reproduire en compilant Tacverif à partir de ses sources et en l'attachant à un debugger ?

Si vous m'envoyez le passe, je peux enquêter moi-même, et vous promettre de le supprimer une fois que cette affaire sera tirée au clair.

2022-01-24 10:14 UTC, closed without merging

2022-02-07 23:24 UTC, nathaner commented
Désolé je n'ai malheureusement pas eu le temps de me pencher sur ce soucis de date. Cependant, j'ai pu faire le test à nouveau avec deux autres certificats de rétablissement et même constat : SaniPasse les indique comme valide un jour trop tôt.