Hash code in memory
lovasoa/sanipasse pull request #61
Opened 2021-08-20 14:47 UTC by XternalSoft

Pour être un peu plus RGPD compliant cette PR va hasher le code avant de l'utiliser comme clé en mémoire. Ainsi, pas de risque d'avoir des données personnelles qui resteraient trop longtemps (tout dépend de la rétention configurée évidemment).

1. Les fonctions sha256 + hex sont déplacées dans un fichier "lib"
2. Et c'est le code hashé qui est utilisé dans "validated_passes'

2021-08-23 19:01 UTC, lovasoa requested changes

2021-08-23 19:01 UTC, lovasoa commented on src/lib/sha256.ts
> +}
Est-ce que l'on pourrait utiliser ces fonctions aussi ici : https://github.com/lovasoa/sanipasse/blob/master/src/routes/_CertificateDGCDetails.svelte#L8-L16

Histoire d'éviter la duplication de code.

2021-08-24 07:49 UTC, hguehl commented on src/lib/sha256.ts
> +}
A la lecture cela semble déjà le cas.. le code https://github.com/lovasoa/sanipasse/blob/master/src/routes/_CertificateDGCDetails.svelte#L8-L16 a été déplacé dans src/lib/sha256.ts et src/routes/_CertificateDGCDetails.svelte  mis à jour en conséquence

2021-08-25 08:54 UTC, lovasoa approved these changes

2021-08-25 09:04 UTC, merged