borne: Ajout de la possibilité d'imprimer des tickets.
lovasoa/sanipasse pull request #70
Opened 2021-08-31 14:55 UTC by LGFdev

Ajoute la possibilité, pour la borne, d'imprimer automatiquement un ticket.

### Configuration de la borne
On peut :
 - activer ou non l'option
 - fixer la largeur du ticket
 - configurer un entête et un pied de page
 
### Le ticket
Il comprend
 - l'entête (s'il est défini)
 - le nom
 - la date de naissance
 - une ligne pour noter le numéro de téléphone pour servir de *cahier de rappel* covid
 - la date et l'heure de la vérification
 - le pied de page (s'il est défini)

pour que le navigateur de la borne imprime automatiquement :
```chromium --kiosk-printing https://sanipasse.fr/```

2021-08-31 16:19 UTC, lovasoa requested changes
C'est une fonctionnalité très intéressante, merci de votre contribution !

J'ai fait quelques remarques techniques ci-dessous.

Et aussi, je n'ai pas encore de CLA formel, mais avant de merger, j'aimerais que vous  assigniez le copyright du code écrit au projet sanipasse et que vous en autorisez la redistribution sans conditions.

2021-08-31 16:19 UTC, lovasoa commented on src/lib/ticket.ts
> +</body>
En faisant du templating directement avec de la manipulation de chaînes de caractères en js, on perd les garanties apportées par la vérification du code à la compilation. Et on empêche de personnaliser le ticket qui est imprimé avec la fonctionnalité de custom CSS. 

Est-ce que l'on pourrait plutôt avoir le ticket qui fait partie du HTML normal de la page, qui utilise le templating par défaut de svelte, et dont l'affichage est géré par une media query css ?

```css
@media screen { /* cacher la div qui contient le ticket */ }
@media print { /* cacher tout sauf la div qui contient le ticket */ }
```

comme ça on peut avoir juste un `/borne/_print_ticket.svelte`, un `<PrintTicket />` dans `_scan.svelte`.

Et lorsque l'on veut imprimer un ticket, on peut juste faire un `window.print()` sans avoir à ouvrir de popup (qui pourrait être bloqué).

2021-09-17 09:26 UTC, LGFdev commented
Le projet a été abandonné par le client. Je n'ai donc plus de crédit temps consacré à ce projet pour faire les modifications.

2021-09-17 10:29 UTC, lovasoa commented
Dommage ! Je suis en contact avec plusieurs entreprises; certaines pourraient être intéressées par le financement de la fonctionnalité; je mettrai la PR à jour si besoin.

2022-01-24 10:14 UTC, closed without merging